### ISSUE TITLE
pip can not install chepy due to lazy-import

### ISSUE THREAD

**Issue by ryanroe** [securisec/chepy#18]
**Describe the bug**
pip can not install chepy , and here is the error stack

```
  Preparing metadata (setup.py) ... done
Collecting base58
  Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting crccheck
  Using cached crccheck-1.1-py3-none-any.whl (29 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting docstring-parser
  Using cached docstring_parser-0.13.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting emoji
  Using cached emoji-1.6.3.tar.gz (174 kB)
  Preparing metadata (setup.py) ... done
Collecting exrex
  Using cached exrex-0.10.5.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... done
Collecting fire==0.4.0
  Using cached fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... done
Collecting lazy-import
  Using cached lazy_import-0.2.2.tar.gz (15 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ryan\AppData\Local\Temp\pip-install-n3w9cm9y\lazy-import_b016669906f64b6b8754dec0e34c1709\setup.py", line 6, in <module>
          readme = infile.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 623: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**
just run 
```
pip install chepy
```

**Expected behavior**
successfully installed

**Screenshots**
![chepy_install_fail](https://user-images.githubusercontent.com/20389952/153327126-c8efefd4-edc1-40f8-aabb-ecc4a0c4477f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (22533.1001)
 - Python Version 3.10.2
 - Chepy Version 3.5

**Additional context**

**Comment by securisec** [comment]
Only python version 3.8 is supported at the moment with the pinned dependency versions. I did test on Mac OS on python 3.10.2 and it installed fine. The issue seems to be more specific with windows decoding gbk issue which I cannot replicate.
