### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by Lem0nDem0n** [securisec/chepy#26]
Hi, I have tried to install Chepy on Windows, but pip3 installation has failed with the following error:
```shell
Preparing metadata (setup.py) ... error

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lipu\AppData\Local\Temp\pip-install-9s51y_zs\lazy-import_33141cce3c0c4752a7b368e8515ea1a2\setup.py", line 6, in <module>
          readme = infile.read()
                   ^^^^^^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 623: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by securisec** [comment]
The current version of Chepy is supported till python version 3.8. Based on the error code, it appears that it in decoding issues in a Windows environment with Chinese characters possibly. There is no way for me to test or support this unfortunately.
