### ISSUE TITLE
pip3 installation does not work

### ISSUE THREAD

**Issue by nmantani** [securisec/chepy#4]
Hi, I have tried to install Chepy on Windows Subsystem for Linux (Ubuntu), but pip3 installation has failed with the following error:

```
$ sudo -H pip3 install chepy
Collecting chepy
  Downloading https://files.pythonhosted.org/packages/b9/1a/1b1a406c6e343018b21d820323897327c56991f17eb383c56ff2c8d347dd/chepy-1.5.0.tar.gz (60kB)
    100% |################################| 61kB 1.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-quz04m03/chepy/setup.py", line 18, in <module>
        requirements = read_requirements()
      File "/tmp/pip-build-quz04m03/chepy/setup.py", line 14, in read_requirements
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-quz04m03/chepy/
$
```

**Comment by securisec** [comment]
@nmantani thanks for the issue. i will push the fix once pypi is up again

**Comment by securisec** [comment]
fixed with https://github.com/securisec/chepy/commit/df83959467d7f21490d893e745cc24956f00aaeb

**Comment by nmantani** [comment]
Thank you for the quick fix! Now Chepy has been installed successfully with pip3.
