### ISSUE TITLE
Chepy does not work without proper chepy.conf

### ISSUE THREAD

**Issue by nmantani** [securisec/chepy#5]
I have tried to execute Chepy CLI after installation, but it has exited with the following error message:

```
$ chepy
Traceback (most recent call last):
  File "/usr/local/bin/chepy", line 11, in <module>
    load_entry_point('chepy==1.5.1', 'console_scripts', 'chepy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/chepy/__init__.py", line 22, in <module>
    _plugins = ChepyConfig().load_plugins()
  File "/usr/local/lib/python3.6/dist-packages/chepy/config.py", line 43, in __init__
    self.plugin_path = self.config["Plugin"]["PluginPath"]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Plugin'
$
```

So I have created ~/.chepy/chepy.conf like this based on the error message and the Chepy document:

```
[Plugin]
pluginpath = None
```

Then the error message has been slightly changed:

```
Traceback (most recent call last):
  File "/usr/local/bin/chepy", line 11, in <module>
    load_entry_point('chepy==1.5.1', 'console_scripts', 'chepy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/chepy/__init__.py", line 22, in <module>
    _plugins = ChepyConfig().load_plugins()
  File "/usr/local/lib/python3.6/dist-packages/chepy/config.py", line 45, in __init__
    self.history_path = self.config["Cli"]["history_path"]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Cli'
```

It seems that Chepy does not work unless I create chepy.conf with proper settings.

**Comment by securisec** [comment]
Hmm.. i tested this in subsystem before release and it worked.. let me check

**Comment by securisec** [comment]
@nmantani can you delete `~/.chepy` and then try running `chepy`?

**Comment by nmantani** [comment]
It worked after deleting ~/.chepy. Thank you so much!

**Comment by nmantani** [comment]
As a side note, I did not manually create empty ~/.chepy directory before the first execution of Chepy CLI. There may be a bug that causes this situation.

**Comment by securisec** [comment]
I think what might have happened was someone an older version of chepy configs were created, but since v 1.5, it has more config options; and thats why it was failing. I can put in a try except in there to forcefully create a new config file, and have opted to do so in case someone is modifying the code. Then it would overwrite their personal configs
